sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql
  - postgresql
  - redis-server

addons:
  postgresql: "9.3"
  mariadb: "10.1"

env:
  - DB=mysql DB_USERNAME=travis
  - DB=pgsql DB_USERNAME=postgres
  - DB=sqlite

before_install:
  - if [[ $TRAVIS_PHP_VERSION == 5.6 ]]; then phpenv config-rm xdebug.ini; fi
  - curl -L https://github.com/kr/beanstalkd/archive/v1.9.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.9/
  - make
  - ./beanstalkd 2>&1 >/dev/null &
  - cd $TRAVIS_BUILD_DIR

install:
  - composer install --no-interaction --no-scripts --prefer-dist --no-suggest

before_script:
    - if [[ "$DB" == "mysql" ]] ; then mysql -e 'CREATE DATABASE deployer;'; fi
    - if [[ "$DB" == "pgsql" ]] ; then psql -c 'CREATE DATABASE deployer;' -U postgres; fi
    - if [[ "$DB" == "sqlite" ]] ; then touch $TRAVIS_BUILD_DIR/database/database.sqlite; fi
    - cp -f .env.example .env
    - php artisan key:generate
    - sed -i 's/APP_ENV=production/APP_ENV=testing/g' .env
    - sed -i 's/APP_DEBUG=false/APP_DEBUG=true/g' .env
    - sed -i "s/DB_CONNECTION=mysql/DB_CONNECTION=$DB/g" .env
    - sed -i "s/DB_USERNAME=deployer/DB_USERNAME=$DB_USERNAME/g" .env
    - sed -i 's/DB_PASSWORD=secret/DB_PASSWORD=/g' .env
    - if [[ "$DB" == "pgsql" ]] ; then sed -i 's/DB_PORT=3306/DB_PORT=5432/g' .env; fi
    - if [[ "$DB" == "sqlite" ]] ; then sed -i 's/DB_DATABASE=deployer//g' .env; fi
    - if [[ "$DB" == "sqlite" ]] ; then sed -i 's/DB_USERNAME=//g' .env; fi
    - if [[ "$DB" == "sqlite" ]] ; then sed -i 's/DB_PASSWORD=//g' .env; fi
    - if [[ "$DB" == "sqlite" ]] ; then sed -i 's/DB_HOST=localhost//g' .env; fi
    - if [[ "$DB" == "sqlite" ]] ; then sed -i 's/DB_PORT=3306//g' .env; fi
    - sed -i 's/SOCKET_SSL_KEY_FILE=//g' .env
    - sed -i 's/SOCKET_SSL_CERT_FILE=//g' .env
    - sed -i 's/SOCKET_SSL_CA_FILE=//g' .env
    - sed -i 's/SOCKET_SSL_KEY_PASSPHRASE=//g' .env
    - sed -i 's/REDIS_PASSWORD=null//g' .env
    - sed -i 's/TRUSTED_PROXIES=//g' .env
    - sed -i 's/GITHUB_OAUTH_TOKEN=//g' .env
    - sed -i 's/GUZZLE_HTTP_PROXY=//g' .env
    - sed -i "s/JWT_SECRET=changeme/JWT_SECRET=$(date +%s | sha256sum | base64 | head -c 32 ; echo)/g" .env
    - sed -i '/^#/ d' .env
    - sed -i 's/ \#default for beanstalkd//g' .env
    - sed -i '/^$/N;/^\n$/D' .env
    - php artisan js-localization:refresh
    - chmod -R 777 storage/ bootstrap/ public/upload/
    - sleep 5
    - php -S 127.0.0.1:8000 -t public/ 2>&1 >/dev/null &

script:
  - php artisan migrate --seed --env="testing"
  - vendor/bin/parallel-lint app/ database/ config/ resources/ tests/ public/
  - vendor/bin/phpcs -p --standard=phpcs.xml
  # - vendor/bin/phpmd app,tests text phpmd.xml
  - if [[ $TRAVIS_PHP_VERSION == 7.0 ]]; then vendor/bin/phpunit --coverage-clover=$TRAVIS_BUILD_DIR/coverage.xml; fi
  - if [[ $TRAVIS_PHP_VERSION != 7.0 ]]; then vendor/bin/phpunit; fi
  - vendor/bin/phpdoccheck --directory=app

after_script:
  - find $TRAVIS_BUILD_DIR/storage/logs/*.log -type f -print -exec cat {} \;
  - cat $TRAVIS_BUILD_DIR/.env

after_success:
  - bash <(curl -s https://codecov.io/bash)
