sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=sqlite
  - DB=sqlite

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/bower_components
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: DB=mysql
      services:
        - mysql
    - php: 7.0
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - postgresql

#before_install:
#  - phpenv config-rm xdebug.ini

install:
  - |
    # Remove PHPStan which doesn't work on 5.6, leave all other packages as we need to be warned about them
    if [[ $(phpenv version-name) = "5.6" ]]; then
      travis_retry composer install --quiet --no-interaction --prefer-dist --no-scripts --ignore-platform-reqs
      composer remove --quiet --no-interaction --no-scripts --dev phpstan/phpstan
      composer update --quiet --no-interaction --lock --no-scripts
      rm -rf $TRAVIS_BUILD_DIR/vendor/
    fi
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - cp -f $TRAVIS_BUILD_DIR/tests/.env.travis $TRAVIS_BUILD_DIR/.env
  - make permissions
  - make travis

script:
  - make lint
  - make migrate
  - make seed
  - make rollback
  - make phpcs
  # - make phpmd
  - make phpunit-ci
  - make phpdoc-check
  - make phpcpd
  - make lines

  # Clear the compiled file and then try to install without the dev dependencies to ensure everything still works
  - travis_retry composer install --no-dev --no-interaction --prefer-dist --no-suggest --quiet
  - php artisan optimize
  - php artisan app:version

after_script:
  - find $TRAVIS_BUILD_DIR/storage/logs/*.log -type f -print -exec cat {} \;
  - cat $TRAVIS_BUILD_DIR/.env

after_success:
  - |
    if [[ -f storage/app/tmp/coverage.xml ]]; then
      mv $TRAVIS_BUILD_DIR/storage/app/tmp/coverage.xml $TRAVIS_BUILD_DIR/coverage.xml
      bash <(curl -s https://codecov.io/bash)
    fi

notifications:
  email: false
