sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1.0

env:
  - DB=sqlite
  - DB=sqlite

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/node_modules
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: DB=mysql
      services:
        - mysql
    - php: 7.0
      env: DB=maria
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=pgsql
      addons:
        postgresql: "9.3"
      services:
        - postgresql

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "7.1.0" ]]; then
      phpenv config-rm xdebug.ini;
    fi

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - travis_retry npm install

before_script:
  - cp -f $TRAVIS_BUILD_DIR/tests/.env.travis $TRAVIS_BUILD_DIR/.env
  - make permissions
  - make travis

script:
  - composer test:lint
  - php artisan migrate
  - php artisan db:seed
  - php artisan migrate:rollback
  - composer test:phpcs
  # - composer test:phpmd
  - make phpunit-ci
  - composer test:phpdoc
  - composer test:phpcpd
  - composer test:loc
  # Clear the compiled file and then try to install without the dev dependencies to ensure everything still works
  - travis_retry composer install --no-dev --no-interaction --prefer-dist --no-suggest --quiet
  - php artisan optimize
  - php artisan app:version

after_script:
  - find $TRAVIS_BUILD_DIR/storage/logs/*.log -type f -print -exec cat {} \;
  - cat $TRAVIS_BUILD_DIR/.env

after_success:
  - |
    if [[ -f storage/app/tmp/coverage.xml ]]; then
      travis_retry composer install --no-interaction --prefer-dist --no-suggest --quiet
      mv $TRAVIS_BUILD_DIR/storage/app/tmp/coverage.xml $TRAVIS_BUILD_DIR/coverage.xml
      php vendor/bin/test-reporter --coverage-report=$TRAVIS_BUILD_DIR/coverage.xml
      bash <(curl -s https://codecov.io/bash)
    fi

notifications:
  email: false
