name: Run

on: [push, pull_request]

jobs:
  run:
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.4
        with:
          php-version: 7.2
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy .env
        run: |
          cp tests/env .env
          touch database/database.sqlite

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Dependency Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install --no-dev --no-interaction --prefer-dist --no-suggest --no-scripts

      - name: Run Artisan
        run: php artisan app:version
